// <auto-generated />
using System;
using CreativeAgency.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreativeAgency.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CreativeAgency.Models.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KorisnikId"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DatumPoslednjegPrijave")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Ime")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("JeAktivan")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MaksimalanBrojAktivnihZadataka")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("KorisnikId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            KorisnikId = 1,
                            DatumKreiranja = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@creativeagency.com",
                            Ime = "Admin",
                            JeAktivan = true,
                            KorisnickoIme = "admin",
                            LozinkaHash = "$2a$11$vBwNZ0QyQJ7cK9qX8YZN7.sYdJx8J0kY6kQ0Wx8kQwO8yX8yX8yX8",
                            MaksimalanBrojAktivnihZadataka = 5,
                            Prezime = "Korisnik"
                        });
                });

            modelBuilder.Entity("CreativeAgency.Models.Projekat", b =>
                {
                    b.Property<int>("ProjekatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjekatId"));

                    b.Property<DateTime?>("DatumAzuriranja")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DatumZavrsetka")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("KreiraoKorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Opis")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ProjekatId");

                    b.HasIndex("KreiraoKorisnikId");

                    b.ToTable("Projekti");

                    b.HasData(
                        new
                        {
                            ProjekatId = 1,
                            DatumKreiranja = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumPocetka = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Kategorija = "Sajt",
                            KreiraoKorisnikId = 1,
                            Naziv = "Primer Projekta",
                            Opis = "Ovo je primer projekta za demonstraciju",
                            Status = "Aktivan"
                        });
                });

            modelBuilder.Entity("CreativeAgency.Models.Views.AktivniProjektiSaZadacimaView", b =>
                {
                    b.Property<int>("ProjekatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjekatId"));

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DatumZavrsetka")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KreatorKorisnickoIme")
                        .HasColumnType("longtext");

                    b.Property<string>("KreatorPunoIme")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ProcenatZavrsenosti")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ProjekatNaziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UkupnoZadataka")
                        .HasColumnType("int");

                    b.Property<int>("ZadaciBlokirani")
                        .HasColumnType("int");

                    b.Property<int>("ZadaciNaCekanju")
                        .HasColumnType("int");

                    b.Property<int>("ZadaciUToku")
                        .HasColumnType("int");

                    b.Property<int>("ZadaciZavrseni")
                        .HasColumnType("int");

                    b.HasKey("ProjekatId");

                    b.ToTable("AktivniProjektiSaZadacimaView");

                    b.ToView("AktivniProjektiSaZadacimaView", (string)null);
                });

            modelBuilder.Entity("CreativeAgency.Models.Views.KorisnikStatistikaView", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KorisnikId"));

                    b.Property<int>("BrojDodjeljenihZadataka")
                        .HasColumnType("int");

                    b.Property<int?>("BrojKasnihZadataka")
                        .HasColumnType("int");

                    b.Property<int>("BrojKreiranihProjеkata")
                        .HasColumnType("int");

                    b.Property<int>("BrojKreiranihZadataka")
                        .HasColumnType("int");

                    b.Property<int?>("BrojZadatakaUToku")
                        .HasColumnType("int");

                    b.Property<int?>("BrojZavrsenihZadataka")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PunoIme")
                        .HasColumnType("longtext");

                    b.HasKey("KorisnikId");

                    b.ToTable("KorisnikStatistikaView");

                    b.ToView("KorisnikStatistikaView", (string)null);
                });

            modelBuilder.Entity("CreativeAgency.Models.Views.ProjektiStatistikaView", b =>
                {
                    b.Property<string>("Kategorija")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("AktivniProjekti")
                        .HasColumnType("int");

                    b.Property<int>("BrojProjеkata")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProcenatZavrsenihZadataka")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("ProjektiNaCekanju")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProsecnoZadatakaPoProjektu")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UkupnoZadataka")
                        .HasColumnType("int");

                    b.Property<int?>("ZavrseniProjekti")
                        .HasColumnType("int");

                    b.HasKey("Kategorija");

                    b.ToTable("ProjektiStatistikaView");

                    b.ToView("ProjektiStatistikaView", (string)null);
                });

            modelBuilder.Entity("CreativeAgency.Models.Views.ZadaciKasneView", b =>
                {
                    b.Property<int>("ZadatakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ZadatakId"));

                    b.Property<int?>("DanaKasni")
                        .HasColumnType("int");

                    b.Property<string>("DodeljenKorisnickoIme")
                        .HasColumnType("longtext");

                    b.Property<int?>("DodeljenKorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("DodeljenPunoIme")
                        .HasColumnType("longtext");

                    b.Property<string>("Prioritet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProjekatId")
                        .HasColumnType("int");

                    b.Property<string>("ProjekatKategorija")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProjekatNaziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RokIzvrsenja")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ZadatakNaslov")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ZadatakId");

                    b.ToTable("ZadaciKasneView");

                    b.ToView("ZadaciKasneView", (string)null);
                });

            modelBuilder.Entity("CreativeAgency.Models.Zadatak", b =>
                {
                    b.Property<int>("ZadatakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ZadatakId"));

                    b.Property<DateTime?>("DatumAzuriranja")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DodeljenKorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("KreiraoKorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Opis")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Prioritet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ProjekatId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RokIzvrsenja")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ZadatakId");

                    b.HasIndex("DodeljenKorisnikId");

                    b.HasIndex("KreiraoKorisnikId");

                    b.HasIndex("ProjekatId");

                    b.ToTable("Zadaci");

                    b.HasData(
                        new
                        {
                            ZadatakId = 1,
                            DatumKreiranja = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            KreiraoKorisnikId = 1,
                            Naslov = "Primer Zadatka",
                            Opis = "Ovo je primer zadatka",
                            Prioritet = "Srednji",
                            ProjekatId = 1,
                            Status = "NaCekanju"
                        });
                });

            modelBuilder.Entity("CreativeAgency.Models.Projekat", b =>
                {
                    b.HasOne("CreativeAgency.Models.Korisnik", "KreiraoKorisnik")
                        .WithMany("KreiraniProjekti")
                        .HasForeignKey("KreiraoKorisnikId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KreiraoKorisnik");
                });

            modelBuilder.Entity("CreativeAgency.Models.Zadatak", b =>
                {
                    b.HasOne("CreativeAgency.Models.Korisnik", "Dodeljen")
                        .WithMany()
                        .HasForeignKey("DodeljenKorisnikId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CreativeAgency.Models.Korisnik", "KreiraoKorisnik")
                        .WithMany("KreiraniZadaci")
                        .HasForeignKey("KreiraoKorisnikId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CreativeAgency.Models.Projekat", "Projekat")
                        .WithMany("Zadaci")
                        .HasForeignKey("ProjekatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dodeljen");

                    b.Navigation("KreiraoKorisnik");

                    b.Navigation("Projekat");
                });

            modelBuilder.Entity("CreativeAgency.Models.Korisnik", b =>
                {
                    b.Navigation("KreiraniProjekti");

                    b.Navigation("KreiraniZadaci");
                });

            modelBuilder.Entity("CreativeAgency.Models.Projekat", b =>
                {
                    b.Navigation("Zadaci");
                });
#pragma warning restore 612, 618
        }
    }
}
